### ISSUE TITLE
Unable to deploy heapster and influxdb

### ISSUE THREAD

**Issue by CoreyMcDonald** [zimmertr/Bootstrap-Kubernetes-with-QEMU#15]
This is a fresh deployment as of last night. I am unable to deploy heapster and influxdb. Running the following versions-

Running pve-manager/6.0-4/2a719255 (running kernel: 5.0.15-1-pve)

https://cdimage.debian.org/cdimage/openstack/current/debian-10.1.2-20190925-openstack-amd64.qcow2

`TASK [Deploying Heapster, InfluxDB, and configuring RBAC for the Dashboard stack.] **********************************************************
ok: [mymaster] => (item=sa_heapster.yml)
ok: [mymaster] => (item=rb_heapster.yml)
ok: [mymaster] => (item=svc_heapster.yml)
ok: [mymaster] => (item=svc_influxdb.yml)
failed: [mymaster] (item=dep_heapster.yml) => {"ansible_loop_var": "item", "changed": false, "item": "dep_heapster.yml", "msg": "Failed to find exact match for extensions/v1beta1.Deployment by [kind, name, singularName, shortNames]"}
failed: [mymaster] (item=dep_influxdb.yml) => {"ansible_loop_var": "item", "changed": false, "item": "dep_influxdb.yml", "msg": "Failed to find exact match for extensions/v1beta1.Deployment by [kind, name, singularName, shortNames]"}`

**Comment by zimmertr** [comment]
Hi, thanks for opening this issue. My ZFS array is currently in a faulted state so I cannot provision anything to test right now but I'll work on evaluating this as soon as I remediate that. 

It is likely that Kubernetes switched around the name of the API that is referenced in that deployment manifest which will have to be updated.

**Comment by zimmertr** [comment]
Hi @CoreyMcDonald, this has been fixed with https://github.com/zimmertr/Bootstrap-Kubernetes-with-QEMU/pull/16

As of [September 18th](https://kubernetes.io/blog/2019/09/18/kubernetes-1-16-release-announcement/), `kubeadm` now supports Kubernetes 1.16. For a while now it has been planned for Heapster to be deprecated in favor of decentralizing monitoring to applications like Prometheus/Grafana. Their [proposed timeline](https://github.com/kubernetes-retired/heapster/blob/master/docs/deprecation.md) was to fully deprecate support by Kubernetes 1.13, however distros were free to discontinue support when they saw fit. It appears that `kuebadm` has elected to deprecate it as of their newest release. 

As a result, I have removed `heapster` and `influxdb` from TKS. I have also upgraded the Dashboard manifest used in the example for the `vars.yml` file. In doing so, the Dashboard will now leverage Metrics Server instead, which has been used internally to offer basic cluster monitoring. If you wish to go beyond that and integrate Grafana, Prometheus, AlertManager, and InfluxDB into your deployment, you can use my personal deployment method which can be found in my other Kubernetes repo [here](https://github.com/zimmertr/Kubernetes-Manifests/tree/master/Grafana). Similar to TKS, it is fully declarative and automated by Ansible.

Thanks again for letting me know about this issue!
